CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
CREATE USER 'blog'@'localhost' IDENTIFIED BY 'adminTTDEMO';
GRANT ALL PRIVILEGES ON blog.* TO 'blog'@'localhost' IDENTIFIED BY 'adminTTDEMO' WITH GRANT OPTION;
FLUSH PRIVILEGES;
